In [1]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.metrics import f1_score
from sklearn.metrics import fbeta_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn import preprocessing
import sklearn as skl

from sklearn.model_selection import cross_val_score

In [24]:
df = pd.read_csv("../datasets/train_radiomics_hipocamp.csv")

In [3]:
df.columns
df.dtypes

ID                                   object
Image                                object
Mask                                 object
diagnostics_Versions_PyRadiomics     object
diagnostics_Versions_Numpy           object
                                     ...   
lbp-3D-k_ngtdm_Contrast             float64
lbp-3D-k_ngtdm_Strength             float64
Sex                                   int64
Age                                 float64
Transition                           object
Length: 2181, dtype: object

In [4]:
df['Transition']

0        CN-CN
1        CN-CN
2        AD-AD
3       CN-MCI
4        CN-CN
        ...   
300      CN-CN
301      CN-CN
302     MCI-AD
303    MCI-MCI
304      CN-CN
Name: Transition, Length: 305, dtype: object

In [36]:
# Selecionar 10 amostras aleatórias de cada categoria
n_samples = 10
df = df.groupby('Transition').sample(n=n_samples, random_state=2021)
df['Transition'].value_counts()

Transition
AD-AD      10
CN-CN      10
CN-MCI     10
MCI-AD     10
MCI-MCI    10
Name: count, dtype: int64

In [26]:
X = df.drop(['Transition'], axis=1)     
y = df['Transition'].to_frame()         

In [27]:
df_numerico = X.select_dtypes(include=[np.number])

from sklearn.preprocessing import StandardScaler,MinMaxScaler
scaler = MinMaxScaler()
df_numerico = pd.DataFrame(scaler.fit_transform(df_numerico), columns=df_numerico.columns, index=df_numerico.index) #normalização
df_numerico.head()

diagnostics_Image-original_Dimensionality  \
110                                        0.0   
251                                        0.0   
282                                        0.0   
81                                         0.0   
129                                        0.0   

     diagnostics_Image-original_Mean  diagnostics_Image-original_Minimum  \
110                         0.246449                                 0.0   
251                         0.570939                                 0.0   
282                         0.712351                                 0.0   
81                          0.583094                                 0.0   
129                         0.402368                                 0.0   

     diagnostics_Image-original_Maximum  diagnostics_Mask-original_VoxelNum  \
110                            0.459770                            0.244510   
251                            0.241379                            0.172289   
282                            0.000000                            0.476341   
81                             0.896552                            0.631198   
129                            0.701149                            0.144442   

     diagnostics_Mask-original_VolumeNum  original_shape_Elongation  \
110                                  0.0                   0.171744   
251                                  0.0                   0.499864   
282                                  0.0                   0.000000   
81                                   0.0                   0.662583   
129                                  0.0                   0.445741   

     original_shape_Flatness  original_shape_LeastAxisLength  \
110                 0.111061                        0.248900   
251                 0.356342                        0.369524   
282                 0.423143                        0.568471   
81                  0.540824                        0.832354   
129                 0.579573                        0.559746   

     original_shape_MajorAxisLength  ...  lbp-3D-k_glszm_ZoneEntropy  \
110                        0.533767  ...                    0.320419   
251                        0.349516  ...                    0.424655   
282                        0.496146  ...                    0.306096   
81                         0.642508  ...                    0.695809   
129                        0.296001  ...                    0.356537   

     lbp-3D-k_glszm_ZonePercentage  lbp-3D-k_glszm_ZoneVariance  \
110                       0.320741                     0.294135   
251                       0.563725                     0.107549   
282                       0.269993                     0.492617   
81                        0.487897                     0.455848   
129                       1.000000                     0.000000   

     lbp-3D-k_ngtdm_Busyness  lbp-3D-k_ngtdm_Coarseness  \
110                 0.310111                   0.433441   
251                 0.240954                   0.515151   
282                 0.567850                   0.203783   
81                  0.423261                   0.263740   
129                 0.033007                   0.925360   

     lbp-3D-k_ngtdm_Complexity  lbp-3D-k_ngtdm_Contrast  \
110                   0.547022                 0.488658   
251                   0.511401                 0.425503   
282                   0.717575                 0.674283   
81                    0.469722                 0.373690   
129                   0.156428                 0.110364   

     lbp-3D-k_ngtdm_Strength  Sex       Age  
110                 0.433929  0.0  0.253731  
251                 0.510575  1.0  0.656716  
282                 0.202072  0.0  0.000000  
81                  0.267255  1.0  0.164179  
129                 0.914894  1.0  1.000000  

[5 rows x 2161 columns]

In [28]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

# Treinar um modelo Random Forest
model = RandomForestClassifier(random_state=2021)
model.fit(df_numerico, y)

# Obter as importâncias das features
feature_importances = pd.DataFrame({
    'Feature': df_numerico.columns,
    'Importance': model.feature_importances_
}).sort_values(by='Importance', ascending=False)

# Mostrar as 10 features mais importantes
#print(feature_importances.head(10))

# Selecionar as n melhores features
n = 500
features_to_keep = feature_importances.iloc[:n]['Feature']

# Filtrar o DataFrame original para manter somente essas features
df_numerico = df_numerico[features_to_keep]

df_numerico.describe()



c:\Users\super\anaconda3\envs\myenv\Lib\site-packages\sklearn\base.py:1473: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


exponential_glrlm_ShortRunEmphasis  \
count                           50.000000   
mean                             0.365246   
std                              0.208117   
min                              0.000000   
25%                              0.204563   
50%                              0.373305   
75%                              0.491711   
max                              1.000000   

       log-sigma-2-0-mm-3D_firstorder_InterquartileRange  \
count                                          50.000000   
mean                                            0.352586   
std                                             0.250004   
min                                             0.000000   
25%                                             0.182546   
50%                                             0.290418   
75%                                             0.512380   
max                                             1.000000   

       log-sigma-2-0-mm-3D_gldm_SmallDependenceEmphasis  \
count                                         50.000000   
mean                                           0.513483   
std                                            0.230593   
min                                            0.000000   
25%                                            0.376721   
50%                                            0.474745   
75%                                            0.647886   
max                                            1.000000   

       log-sigma-1-0-mm-3D_gldm_SmallDependenceEmphasis  \
count                                         50.000000   
mean                                           0.459801   
std                                            0.243728   
min                                            0.000000   
25%                                            0.302733   
50%                                            0.443112   
75%                                            0.604118   
max                                            1.000000   

       log-sigma-2-0-mm-3D_firstorder_RobustMeanAbsoluteDeviation  \
count                                          50.000000            
mean                                            0.336730            
std                                             0.236620            
min                                             0.000000            
25%                                             0.171235            
50%                                             0.263307            
75%                                             0.513195            
max                                             1.000000            

       wavelet-LLL_glrlm_RunVariance  \
count                      50.000000   
mean                        0.449920   
std                         0.243788   
min                         0.000000   
25%                         0.293439   
50%                         0.409289   
75%                         0.592260   
max                         1.000000   

       exponential_glrlm_ShortRunHighGrayLevelEmphasis  \
count                                        50.000000   
mean                                          0.154557   
std                                           0.156312   
min                                           0.000000   
25%                                           0.076470   
50%                                           0.118607   
75%                                           0.182158   
max                                           1.000000   

       log-sigma-5-0-mm-3D_glszm_GrayLevelNonUniformity  \
count                                         50.000000   
mean                                           0.297561   
std                                            0.239582   
min                                            0.000000   
25%                                            0.125409   
50%                                            0.215361   
75%                                            0.396413   
max               

In [ ]:
#Retirar uma das features de um par com mais de 80% de correlação
corr_matrix = df_numerico.corr().abs()
upper_tri = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
to_drop = [column for column in upper_tri.columns if any(upper_tri[column] > 0.8)]
df_numerico = df_numerico.drop(columns=to_drop)

In [40]:
from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, f1_score
import numpy as np

# Definindo o classificador
clf = DecisionTreeClassifier(criterion='gini', max_depth=10, random_state=2021)

# Listas para armazenar as métricas
scores = []
f1_scores = []

# Utilizando StratifiedKFold para garantir o balanceamento entre as classes
kf = StratifiedKFold(n_splits=3)

# Loop de treinamento e avaliação
for train, test in kf.split(df_numerico, y):
    clf.fit(df_numerico.iloc[train], y.iloc[train])  # Ajustando as divisões corretamente
    score = clf.score(df_numerico.iloc[train], y.iloc[train])
    scores.append(score)
    
    y_predicted = clf.predict(df_numerico.iloc[test])  # Fazendo a predição
    print("Confusion Matrix:")
    print(confusion_matrix(y.iloc[test], y_predicted))  # Confusion Matrix para o conjunto de teste
    
    f1 = f1_score(y.iloc[test], y_predicted, average='weighted')  # F1-Score ponderado para desbalanceamento
    f1_scores.append(f1)
    print(f"F1-Score: {f1:.2f}")
    print(f"Train Accuracy: {score:.2f}")

# Resultados finais
print("\nRESULT: %0.2f accuracy with a std deviation of %0.2f" % (np.mean(scores), np.std(scores)))
print("F1-Score: %0.2f with a std deviation of %0.2f" % (np.mean(f1_scores), np.std(f1_scores)))


Confusion Matrix:
[[4 0 0 0 0]
 [0 1 0 0 2]
 [0 0 1 0 2]
 [1 0 0 1 2]
 [0 0 0 1 2]]
F1-Score: 0.53
Train Accuracy: 1.00
Confusion Matrix:
[[1 1 0 1 0]
 [0 3 1 0 0]
 [0 2 1 0 0]
 [0 0 1 2 0]
 [0 1 0 2 1]]
F1-Score: 0.46
Train Accuracy: 1.00
Confusion Matrix:
[[3 0 0 0 0]
 [1 1 0 0 1]
 [0 0 3 1 0]
 [0 0 1 1 1]
 [1 0 0 1 1]]
F1-Score: 0.55
Train Accuracy: 1.00

RESULT: 1.00 accuracy with a std deviation of 0.00
F1-Score: 0.51 with a std deviation of 0.04


In [7]:

clf = DecisionTreeClassifier(random_state=2021)
clf.fit(df_numerico, y)
print(clf.get_depth())

10


In [8]:
X_test = pd.read_csv("../datasets/test_radiomics_hipocamp.csv")
X_test = X_test.select_dtypes(include=[np.number])

In [9]:
predictions = clf.predict(X_test)

In [10]:
predictions

array(['MCI-AD', 'MCI-MCI', 'CN-CN', 'CN-CN', 'MCI-MCI', 'MCI-AD',
       'AD-AD', 'CN-CN', 'AD-AD', 'MCI-MCI', 'CN-CN', 'CN-CN', 'CN-CN',
       'CN-CN', 'CN-CN', 'MCI-AD', 'CN-CN', 'MCI-AD', 'MCI-AD', 'MCI-AD',
       'MCI-AD', 'MCI-MCI', 'CN-CN', 'MCI-MCI', 'MCI-MCI', 'CN-CN',
       'AD-AD', 'CN-CN', 'CN-CN', 'CN-CN', 'CN-MCI', 'MCI-MCI', 'CN-CN',
       'MCI-MCI', 'MCI-MCI', 'MCI-MCI', 'AD-AD', 'MCI-MCI', 'CN-CN',
       'CN-CN', 'MCI-MCI', 'CN-CN', 'AD-AD', 'CN-CN', 'CN-CN', 'CN-MCI',
       'MCI-MCI', 'MCI-MCI', 'AD-AD', 'AD-AD', 'MCI-AD', 'MCI-AD',
       'MCI-MCI', 'MCI-MCI', 'CN-CN', 'MCI-MCI', 'CN-CN', 'MCI-MCI',
       'MCI-AD', 'MCI-AD', 'CN-CN', 'MCI-MCI', 'CN-CN', 'MCI-AD', 'CN-CN',
       'CN-CN', 'CN-CN', 'CN-CN', 'MCI-AD', 'CN-CN', 'MCI-AD', 'AD-AD',
       'CN-CN', 'MCI-AD', 'AD-AD', 'MCI-AD', 'MCI-AD', 'MCI-MCI', 'CN-CN',
       'MCI-AD', 'AD-AD', 'MCI-AD', 'AD-AD', 'CN-CN', 'AD-AD', 'MCI-MCI',
       'AD-AD', 'MCI-AD', 'MCI-MCI', 'CN-CN', 'AD-AD', 'MCI-MCI',
      

In [11]:
data = pd.DataFrame({
    'RowId': np.arange(1, len(predictions) + 1), 
    'Result': predictions
})

#data.to_csv('decision_tree_predicts_maxdepth6.csv', index=False)